---
# This playbook will install Apache Web Server
- name: httpd_deploy_to_aws_ami
  hosts: all
  tasks:
  - name: Install HTTPD
    yum:
      name: "{{ item }}"
      state: latest
    loop:
     - httpd
    when: ansible_os_family == "RedHat"

  - name: Setting default HTTP Server page
    shell: echo "<h1>This Page Install by AWS SSM using with Ansible </h1>" > /var/www/html/index.html

  - name: Starting Apache Webserver
    service:
      name: httpd
      state: restarted

  - name: enabling apache on startup
    service: name=httpd enabled=yes state=started
    when: ansible_os_family == "RedHat"