---
# Playbook will install Apache Web Server
- name: httpd_deploy_to_aws_ami
  hosts: all
  tasks:
  - name: Install HTTPD
    yum:
      name: "{{ item }}"
      state: latest
    loop:
     - httpd
    when: ansible_os_family == "RedHat"

  - name: Setting default HTTP Server pages-1
    shell: echo "<h1>This Page Installed by AWS SSM using with Ansible </h1>" > /var/www/html/index.html
    
  - name: Setting default HTTP Server pages-2
    shell: curl http://169.254.169.254/latest/meta-data/instance-id | cut -d " " -f1 >> /var/www/html/index.html
    
  - name: Setting default HTTP Server pages-3
    shell: curl http://169.254.169.254/latest/meta-data/local-ipv4 | cut -d " " -f1 >> /var/www/html/index.html

  - name: Setting default HTTP Server pages-4
    shell: curl http://169.254.169.254/latest/meta-data/public-ipv4 | cut -d " " -f1 >> /var/www/html/index.html

  - name: Setting default HTTP Server pages-4
    shell: sed -i 's/^/<i>/' /var/www/html/index.html && sed -i 's/$/<\/i><br>/' /var/www/html/index.html
    
 
  - name: Starting Apache Webserver
    service:
      name: httpd
      state: restarted

  - name: enabling apache on startup
    service: name=httpd enabled=yes state=started
    when: ansible_os_family == "RedHat"
